### ISSUE TITLE
Fail to build with QT 5.7

### ISSUE THREAD

**Issue by marillat** [mbunkus/mkvtoolnix#1812]
Hi,
From debian bug report https://bugs.debian.org/844660

```
In file included from src/common/common_pch.h:4:0:
src/info/ui/mainwindow.h: In member function ‘void Ui_main_window::retranslateUi(QMainWindow*)’:
src/common/common.h:81:45: error: ‘pgettext’ was not declared in this scope
 #  define PY(context, s) pgettext(context, s)
                                             ^
src/common/qt.h:28:32: note: in expansion of macro ‘PY’
 #define QPTR(s, context) to_qs(PY(context, s))
                                ^~
src/info/ui/mainwindow.h:106:37: note: in expansion of macro ‘QPTR’
         main_window->setWindowTitle(QPTR("mkvInfo", Q_NULLPTR));
                                     ^
compilation terminated due to -Wfatal-errors.
In file included from src/common/common_pch.h:4:0:
src/info/ui/mainwindow.h: In member function ‘void Ui_main_window::retranslateUi(QMainWindow*)’:
src/common/common.h:81:45: error: ‘pgettext’ was not declared in this scope
 #  define PY(context, s) pgettext(context, s)
                                             ^
src/common/qt.h:28:32: note: in expansion of macro ‘PY’
 #define QPTR(s, context) to_qs(PY(context, s))
                                ^~
src/info/ui/mainwindow.h:106:37: note: in expansion of macro ‘QPTR’
         main_window->setWindowTitle(QPTR("mkvInfo", Q_NULLPTR));
                                     ^
compilation terminated due to -Wfatal-errors.
```

**Comment by mbunkus** [comment]
I can and actually do build with Qt 5.7 just fine, albeit on Arch Linux.

Looking more closely at your error message shows something rather strange — the fact that `QPTR` is still present in the `.h` file even though it should have been removed by the build process when creating said `.h` from the corresponding `.ui` file. Have you run `uic` manually at some point?

Anyway. Some of those translation macros are really outdated. I've just removed `QPTR`, `PY`, `PNY`, and streamlined the process of generating those `.h` from the `.ui` files. You can apply 28c5f06597f011e9f2aa38c5ae2994d9f36b6576 on your end and try building again from a clean source tree.

**Comment by marillat** [comment]
No never run uic. This virtualbox machine is only used to build debian package.
Thanks for the fix. I'll upload a new package today.

**Comment by mbunkus** [comment]
Can I interpret that as "yes, the commit fixes the issue"?

**Comment by marillat** [comment]
Now yes, the build is done without problem.
Thanks again.

**Comment by mbunkus** [comment]
Great, and you're welcome. Thanks for reporting it.
