### ISSUE TITLE
failure trying to build on FreeBSD < 10.0-RELEASE

### ISSUE THREAD

**Issue by ehaupt** [mbunkus/mkvtoolnix#1243]
Trying to build mkvtoolnix 7.9.0 on FreeBSD (lower versions than 10.x) both 32/64 bit I am seeing the following build failure:

```
g++48 -Wall -Wno-comment -Wfatal-errors -Wlogical-op -O3 -D_FILE_OFFSET_BITS=64 -DMTX_LOCALE_DIR=\"/usr/local/share/locale\" -DMTX_PKG_DATA_DIR=\"/usr/local/share/mkvtoolnix\" -DMTX_DOC_DIR=\"/usr/local/share/doc/mkvtoolnix\" -I/usr/local/include -std=c++11 -Wnon-virtual-dtor -Woverloaded-virtual -Wextra -Wno-missing-field-initializers -I/usr/local/lib/wx/include/gtk2-unicode-3.0 -I/usr/local/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -D_THREAD_SAFE -I/usr/local/include -O2 -pipe -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing -Wl,-rpath=/usr/local/lib/gcc48 -I. -Ilib -Ilib/avilib-0.6.10 -Isrc -Ilib/utf8-cpp/source -Ilib/pugixml/src -c -MMD -MF ./rake.d/dependency.d/tmp/src_merge_cluster_helper_o.d -o src/merge/cluster_helper.o -x c++ src/merge/cluster_helper.cpp
In file included from src/merge/generic_reader.h:26:0,
                 from src/input/r_aac.h:22,
                 from src/merge/reader_detection_and_creation.cpp:19:
src/merge/timecode_factory.h: In constructor 'forced_default_duration_timecode_factory_c::forced_default_duration_timecode_factory_c(int64_t, const timecode_sync_t&, const string&, int64_t)':
src/merge/timecode_factory.h:190:26: error: 'llround' is not a member of 'std'
     , m_default_duration{std::llround(default_duration * tcsync.numerator / tcsync.denominator)}
                          ^
compilation terminated due to -Wfatal-errors.
In file included from src/merge/generic_packetizer.h:26:0,
                 from src/merge/generic_packetizer.cpp:35:
src/merge/timecode_factory.h: In constructor 'forced_default_duration_timecode_factory_c::forced_default_duration_timecode_factory_c(int64_t, const timecode_sync_t&, const string&, int64_t)':
src/merge/timecode_factory.h:190:26: error: 'llround' is not a member of 'std'
     , m_default_duration{std::llround(default_duration * tcsync.numerator / tcsync.denominator)}
                          ^
compilation terminated due to -Wfatal-errors.
In file included from src/merge/generic_reader.h:26:0,
                 from src/merge/mkvmerge.cpp:62:
src/merge/timecode_factory.h: In constructor 'forced_default_duration_timecode_factory_c::forced_default_duration_timecode_factory_c(int64_t, const timecode_sync_t&, const string&, int64_t)':
src/merge/timecode_factory.h:190:26: error: 'llround' is not a member of 'std'
     , m_default_duration{std::llround(default_duration * tcsync.numerator / tcsync.denominator)}
                          ^
compilation terminated due to -Wfatal-errors.
In file included from src/merge/generic_packetizer.h:26:0,
                 from src/merge/output_control.cpp:65:
src/merge/timecode_factory.h: In constructor 'forced_default_duration_timecode_factory_c::forced_default_duration_timecode_factory_c(int64_t, const timecode_sync_t&, const string&, int64_t)':
src/merge/timecode_factory.h:190:26: error: 'llround' is not a member of 'std'
     , m_default_duration{std::llround(default_duration * tcsync.numerator / tcsync.denominator)}
                          ^
compilation terminated due to -Wfatal-errors.
In file included from src/merge/generic_packetizer.h:26:0,
                 from src/merge/generic_reader.cpp:17:
src/merge/timecode_factory.h: In constructor 'forced_default_duration_timecode_factory_c::forced_default_duration_timecode_factory_c(int64_t, const timecode_sync_t&, const string&, int64_t)':
src/merge/timecode_factory.h:190:26: error: 'llround' is not a member of 'std'
     , m_default_duration{std::llround(default_duration * tcsync.numerator / tcsync.denominator)}
                          ^
compilation terminated due to -Wfatal-errors.
src/merge/packet.cpp: In member function 'void packet_t::normalize_timecodes()':
src/merge/packet.cpp:26:15: error: 'llround' is not a member of 'std'
   timecode                     = RND_TIMECODE_SCALE(timecode);
               ^
compilation terminated due to -Wfatal-errors.
In file included from src/merge/timecode_factory.cpp:20:0:
src/merge/timecode_factory.h: In constructor 'forced_default_duration_timecode_factory_c::forced_default_duration_timecode_factory_c(int64_t, const timecode_sync_t&, const string&, int64_t)':
src/merge/timecode_factory.h:190:26: error: 'llround' is not a member of 'std'
     , m_default_duration{std::llround(default_duration * tcsync.numerator / tcsync.denominator)}
                          ^
compilation terminated due to -Wfatal-errors.
In file included from src/merge/generic_packetizer.h:26:0,
                 from src/output/p_video.h:19,
                 from src/merge/cluster_helper.cpp:28:
src/merge/timecode_factory.h: In constructor 'forced_default_duration_timecode_factory_c::forced_default_duration_timecode_factory_c(int64_t, const timecode_sync_t&, const string&, int64_t)':
src/merge/timecode_factory.h:190:26: error: 'llround' is not a member of 'std'
     , m_default_duration{std::llround(default_duration * tcsync.numerator / tcsync.denominator)}
                          ^
compilation terminated due to -Wfatal-errors.
*** Error code 1
```
This is after applying the patches from  #1215

**Comment by ehaupt** [comment]
cmath doesn't make llround visible because _GLIBCXX_USE_C99_MATH_TR1 is not defined on FreeBSD 8/9. It can be solved by replacing std::llround with llround.

**Comment by mbunkus** [comment]
Well, `std::llround` in `cmath` is a C++11 feature. MKVToolNix requires C++11, so if that compiler is too old to define it then I won't implement workarounds for it – especially as you already have a workaround that you can apply locally.
