### ISSUE TITLE
8.2.0 fails to compile without curl support

### ISSUE THREAD

**Issue by jspaces** [mbunkus/mkvtoolnix#1359]
The 8.2.0 version fails to compile on Arch Linux x86_64 with qt v5.5.0 with the following error.

src/mkvtoolnix-gui/main_window/main_window.cpp: In member function ‘virtual void mtx::gui::MainWindow::setupMenu()’:
src/mkvtoolnix-gui/main_window/main_window.cpp:121:7: error: ‘class mtx::gui::Ui::MainWindow’ has no member named ‘actionGUICheckForUpdates’
   ui->actionGUICheckForUpdates->setVisible(false);

compilation terminated due to -Wfatal-errors.

I also tried the latest git version 8342.c9fed48 with the same error.

**Comment by mbunkus** [comment]
Dang. Thanks for the report. I didn't catch it because I always compile with curl support.

Rename that variable to `actionHelpCheckForUpdates`; that's the fix I'll push in a bit.

**Comment by mbunkus** [comment]
Please give the linked patch a try and shout if it doesn't fix the issue for you.
