### ISSUE TITLE
Unable to build branch 'master' with GCC 5.3.0 and boost 1.48.0

### ISSUE THREAD

**Issue by SchweinDeBurg** [mbunkus/mkvtoolnix#2037]
```
         CXX src/common/xml/xml.cpp
src/common/xml/xml.cpp: In function ‘mtx::xml::document_cptr mtx::xml::load_file(const string&, unsigned int, boost::optional<long long int>)’:
src/common/xml/xml.cpp:83:67: error: no matching function for call to ‘std::basic_string<char>::replace(const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, const __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >&, const char [6])’
       content.replace(matches[1].first, matches[1].second, "UTF-8");
                                                                   ^
compilation terminated due to -Wfatal-errors.

```

**Comment by mbunkus** [comment]
Boost 1.48.0 is rather old (it was released in 2011, and all of the distributions I officially support include newer versions). I will likely not support such old versions in the future. Please upgrade your copy of Boost.

That being said: I will fix this particular issue as it's easy enough to do so.

**Comment by mbunkus** [comment]
*sigh* I cannot even compile Boost 1.48.0 with gcc 5.3.1. I will therefore not be able to actually test my fix. It works with newer versions, and according to 1.48.0's documentation it should work with 1.48.0, too.

If the fix doesn't work for you, then you'd be best served if you created one yourself.

**Comment by SchweinDeBurg** [comment]
Thank You very much! I've just successfully built mkvtoolnix with boost 1.48.0.

**Comment by mbunkus** [comment]
You're welcome.
